FROM bde2020/spark-master:3.0.0-hadoop3.2

# Copy your application files into the container
COPY ./shared_data /shared_data

# Set the working directory
WORKDIR /shared_data

# Define the command to run your Spark application
CMD ["/spark/bin/spark-submit", "main.py"]